version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: PowerCo/tokenizer
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/cmd/broker"
    schedule:
      interval: "daily"
